COSENT_LOSS = "cosent"
COSINE_LOSS = "cosine"
ANGLE_LOSS = "angle"
CONTRASTIVE_TENSION_LOSS = "ContrastiveTensionLossInBatchNegatives"
MULTIPLE_NEGATIVE_RANKING_LOSS = "MultipleNegativesRankingLoss"

SUPERVISED_LOSSES = [
    COSENT_LOSS,
    COSINE_LOSS,
    ANGLE_LOSS,
]

UNSUPERVISED_LOSSES = [
    CONTRASTIVE_TENSION_LOSS,
    MULTIPLE_NEGATIVE_RANKING_LOSS,
]
